[package]
name = "forge-conference-processor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
forge-core = { path = "../forge-core" }
forge-mixer = { path = "../forge-mixer" }
forge-recorder = { path = "../forge-recorder" }

bytes = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tempfile = "3.8"
