[package]
name = "forge-transcoder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
forge-core = { path = "../forge-core" }
forge-codecs = { path = "../forge-codecs" }
forge-resampler = { path = "../forge-resampler" }

bytes = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
